### ISSUE TITLE
Ability to disable directory trim.

### ISSUE THREAD

**Issue by moonrumble** [agkozak/agkozak-zsh-prompt#13]
Currently, there is no way to disable directory trimming. I can set an arbitrary high number. How can i just disable that functionality?

May be settting `AGKOZAK_PROMPT_DIRTRIM=0` or negative number should disable it?

**Comment by agkozak** [comment]
That's a smart idea. I'll work on it. Thanks.

**Comment by agkozak** [comment]
I put together something on the `develop` branch like what you described. See if you like it.

**Comment by agkozak** [comment]
I just pushed another commit (bug fix).

**Comment by moonrumble** [comment]
for some reason, It is still not working. I just tested with commit `eaf7498`

**Comment by agkozak** [comment]
It should be working -- yes, that is the latest commit. For me, it changes behavior as soon as I type

    AGKOZAK_PROMPT_DIRTRIM=0

Just as a test, go to a directory with a fairly long name (such as `/usr/local/share/zshelldoc`) and type the following

    _agkozak_prompt_dirtrim 0
    _agkozak_prompt_dirtrim 1
    _agkozak_prompt_dirtrim 2

and see what the responses are. (You might also want to type

    zsh

first just to make sure you've got the latest version of the prompt loaded correctly).

**Comment by moonrumble** [comment]
It is working now as expected.
